from django.urls import path
from . import views
from . import views_add_cycle_only
app_name = "customers"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/filter/<slug:kind>/", views.dashboard_filter, name="dashboard_filter"),
    path("", views.customer_list, name="customer_list"),
    path("bulk-trash/", views.customers_bulk_trash, name="customers_bulk_trash"),
    path("calendar/", views.calendar_home, name="calendar_home"),
    path("calendar/prefs/", views.calendar_prefs, name="calendar_prefs"),
    path("calendar/update/<int:consultation_id>/", views.calendar_update_reservation, name="calendar_update_reservation"),
    path("api/reservation-conflict/", views.api_reservation_conflict, name="api_reservation_conflict"),
    path("api/inventory/manufacturers/", views.api_inventory_manufacturers, name="api_inventory_manufacturers"),
    path("api/inventory/units/", views.api_inventory_units, name="api_inventory_units"),
    path("api/inventory/unit-by-serial/", views.api_inventory_unit_by_serial, name="api_inventory_unit_by_serial"),
    path("api/notifications/mark-read/", views.api_notifications_mark_read, name="api_notifications_mark_read"),
    path("center-events/create/", views.center_event_create, name="center_event_create"),
    path("center-events/<int:event_id>/update/", views.center_event_update, name="center_event_update"),
    # 'delete'는 삭제가 아니라 취소(로그 보존)로 동작합니다.
    path("center-events/<int:event_id>/delete/", views.center_event_cancel, name="center_event_delete"),
    path("center-events/<int:event_id>/cancel/", views.center_event_cancel, name="center_event_cancel"),
    path("settings/", views.settings_home, name="settings_home"),
    path("settings/profile/", views.settings_profile, name="settings_profile"),
    path("settings/profile/reveal-rrn/", views.settings_profile_reveal_rrn, name="settings_profile_reveal_rrn"),
    path("settings/access-logs/", views.settings_access_logs, name="settings_access_logs"),
    path("settings/inventory-history/", views.settings_inventory_history, name="settings_inventory_history"),
    path("settings/upload-management/", views.settings_upload_management, name="settings_upload_management"),
    path("settings/upload-management/template/<slug:kind>/", views.settings_upload_management_template, name="settings_upload_management_template"),
    path("settings/upload-management/api/upload/", views.api_customer_csv_upload, name="api_customer_csv_upload"),
    path("settings/sales-analysis/", views.sales_analysis, name="sales_analysis"),
    path("settings/sales-analysis/vat-export/", views.sales_analysis_vat_export, name="sales_analysis_vat_export"),
    path("settings/trash/", views.trash_list, name="trash_list"),
    path("settings/trash/bulk-restore/", views.trash_bulk_restore, name="trash_bulk_restore"),
    path("settings/trash/bulk-purge/", views.trash_bulk_purge, name="trash_bulk_purge"),
    path("settings/trash/<int:pk>/restore/", views.trash_restore, name="trash_restore"),
    path("settings/trash/<int:pk>/purge/", views.trash_purge, name="trash_purge"),
    path("stage/exam/", views.stage_exam_list, name="stage_exam_list"),
    path("stage/payment/", views.stage_payment_list, name="stage_payment_list"),
    path("stage/nhis/", views.stage_nhis_list, name="stage_nhis_list"),
    path("stage/followup/", views.stage_followup_list, name="stage_followup_list"),
    path("inventory/", views.inventory_home, name="inventory_home"),
    path("as/", views.after_service_list, name="after_service_list"),
    path("new/", views.customer_create, name="create"),
    path("<int:pk>/clear-product/", views.clear_product_payment, name="clear_product_payment"),
    path("<int:pk>/add-cycle/", views_add_cycle_only.customer_add_cycle, name="add_cycle"),
    path("documents/general/public/<int:case_id>/", views.download_general_public_documents, name="download_general_public_documents"),
    path("documents/general/aftercare/<int:case_id>/<int:round_no>/", views.download_general_aftercare_documents, name="download_general_aftercare_documents"),
    path("<int:pk>/", views.customer_detail, name="customer_detail"),
]
