# Generated by ChatGPT for migration graph merge
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_followup_manager_progress"),
        ("customers", "0002_inventoryproductmodel_importer_name"),
    ]

    operations = [
    ]
