# Generated by ChatGPT on 2026-03-05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_merge_0002_followup_manager_progress_0002_inventoryproductmodel_importer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudiogramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='검사일시')),
                ('points_mode', models.IntegerField(choices=[(7, '7pt'), (11, '11pt')], default=7, verbose_name='포인트')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiogram_sessions', to='customers.customer', verbose_name='고객')),
            ],
            options={
                'verbose_name': '오디오그램 검사',
                'verbose_name_plural': '오디오그램 검사',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AudiogramPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_hz', models.IntegerField(verbose_name='주파수(Hz)')),
                ('right_db', models.IntegerField(blank=True, null=True, verbose_name='우(dB)')),
                ('left_db', models.IntegerField(blank=True, null=True, verbose_name='좌(dB)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='customers.audiogramsession', verbose_name='오디오그램 검사')),
            ],
            options={
                'verbose_name': '오디오그램 포인트',
                'verbose_name_plural': '오디오그램 포인트',
                'ordering': ['frequency_hz'],
                'unique_together': {('session', 'frequency_hz')},
            },
        ),
    ]
