# Generated by Django 4.2.29 on 2026-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_extend_audiogram_point_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiogrampoint',
            name='left_db',
            field=models.IntegerField(blank=True, null=True, verbose_name='기도(좌)'),
        ),
        migrations.AlterField(
            model_name='audiogrampoint',
            name='right_db',
            field=models.IntegerField(blank=True, null=True, verbose_name='기도(우)'),
        ),
    ]
